### ISSUE TITLE
Memory rows should be represented as numerated grooves

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#17]
Grooves are better adjusted to round shapes of the tubes. They may save space also.

**Comment by jeissonh** [comment]
Esta discusión la podemos tener por Skype. La idea es que los estantes sean redondos, ajustados para albergar tubos neumáticos; y no cuadrados como para albergar libros. Estas imágenes nos pueden dar ideas:

![wine rack](http://image.made-in-china.com/2f0j00MsLaGiHchUbw/Metal-Wine-Racks-of-Domestic-HK-WR-1448-.jpg)

![wine rack 2](http://www.alambika.ca/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/a/bali_wine_rack.jpg)

Sería como la segunda, sólo que un único surco alargado, y con espacio para escribir las direcciones de memoria.

**Comment by aph26** [comment]
![boceto_mesacompartida](https://cloud.githubusercontent.com/assets/9001568/6831037/714b5c0e-d2e3-11e4-9649-a18152cb23f0.jpg)

¿Algo así?

**Comment by aph26** [comment]
a ver si le entendí bien,sería hacer los estantes algo así? 

![bocet_estante](https://cloud.githubusercontent.com/assets/9001568/7103623/985d1912-e06d-11e4-9b24-9c84da087646.jpg)

**Comment by jeissonh** [comment]
No. Aunque ese está muy bonito.
No es un estante para libros, sino para tubos. Voy a tratar de hacer un dibujo y subir una fotografía aquí...

**Comment by aph26** [comment]
Ok, que dicha porque si la disposición de los data types fuera en vertical, tendríamos problemas para hacer los datos más grandes...

**Comment by jeissonh** [comment]
La idea es que los estantes parezcan como canoas, o más bien, hechos como de tejas. Las tejas tienen forma curva. Por eso deben tener cierta sensación de profundidad (sombras). En el borde inferior se escriben las direcciones de memoria. En un techo, las tejas se ponen de tal forma que un extremo queda debajo y el otro encima de sus vecinas. Aquí no. Las tejas estarían una al lado de la otra, formando un continuo donde se pueden poner los tubos neumáticos con datos.

![estantes-tubos](https://cloud.githubusercontent.com/assets/5830477/7103706/037135fc-e083-11e4-9d23-ecd78c11e38c.jpg)

Cada teja podría tener el tamaño de 8 bytes. Es decir, el sheft_middle sería de un ancho de 8 bytes y en el extremo derecho una pequeña "ranura" que da la sensación de que inicia otra teja. El shelf_left tendría el borde y el shelf_right el borde derecho, que debe coincidir con la ranura derecha.

¿Qué opinas?

**Comment by aph26** [comment]
Ok, de momento suena bien, vamos a ver qué resulta entonces...

**Comment by aph26** [comment]
A ver qué tal así... Un ejemplo de 3 niveles del estante y recortado a lo ancho, del lado izquierdo puede ver la terminación del estante abierta, mientras que en la derecha es cerrada, cuál le funciona mejor? 

![boceto_estante_curvo](https://cloud.githubusercontent.com/assets/9001568/7105813/caedc6ee-e0e8-11e4-9961-5f9cc9989bd0.jpg)

**Comment by jeissonh** [comment]
Esto está mucho más natural y futurista! Me parece muy bien el extremo derecho. Esa forma de tabla ayuda a la sensación de profundidad. Sugerencias:

1. Reducir la altura para los datos. La altura puede ser 6 pixeles más que la altura de un struct_middle.svg. A lo sumo 8 pixeles más.
2. Hacer los bordes superior e inferior de las tejas de igual tamaño. Yo pienso escribir números en la parte inferior. Si en la parte superior se puede escribir algo, lo aprovecho para escribir nombres de variables.
3. La división entre tejas no es natural. Me parece una varilla de construcción encima de todas las canoas. Si es posible hacerla redondeada, mejor.

**Comment by aph26** [comment]
![previa_shelf](https://cloud.githubusercontent.com/assets/9001568/7217621/9055c282-e5f4-11e4-9809-68e41696a9e6.jpg)

**Comment by jeissonh** [comment]
Estos estantes están geniales. La forma circular encaja muy bien con la idea de los tubos, y el diseño es futurista, acorde a los robots, siento yo.

Tenemos un problema con la separación entre estantes. No puede haber una separación entre el byte 0 y el byte 1. Se me ocurre que la separación, debe estar independiente, en su propia imagen, cuyo ancho es el de 1 byte. El shelf_middle ocuparía 7 un ancho de bytes. De esta forma, yo asigno las separaciones mediante software. He creado el issue #81 para seguir la tarea ahí.

Otra tarea que queda ahora es hacer el resto de elementos de la interfaz (las mesas acordes al diseño de los estantes. En especial, asignarles colores y sombras. He creado el issue #82 para ello.
