### ISSUE TITLE
Adjust table color for Data segment

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#18]
Color of the shared_table.svg should be the same than labels in shelf_middle.svg. El segmento de datos (shared_table.svg) también tiene estantes, y por tanto, el color de la mesa debería ser el mismo color donde van las etiquetas (direcciones de memoria) en los estantes. En el shared_table.svg que está en el repositorio, yo hice ese cambio y además obscurecí las patas de la mesa. Pero haz los cambios que consideres pertinentes para mantener la uniformidad.

**Comment by aph26** [comment]
![shelf_table](https://cloud.githubusercontent.com/assets/9001568/6828437/792af958-d2d3-11e4-8339-179d5ec5fcc0.jpg)

Con base en el screenshot, que me compartió, creo que la idea de ahora incorporar estantes en la "shared_table" nos va a generar problemas visuales, por la discrepancia entre perspectivas. En el sentido de que si el estante es visible para el usuarios (jugador), no podría serlo para los robots.

**Comment by jeissonh** [comment]
En el issue #17 hay una sugerencia de representar los estantes como "surcos" para poner los tubos neumáticos. Eso permite tanto al jugador como a los robots ver lo que hay en los segmentos desde sus perspectivas, creo yo.

**Comment by aph26** [comment]
![boceto_mesacompartida](https://cloud.githubusercontent.com/assets/9001568/6830933/d9369e24-d2e2-11e4-81c3-0f6dfd77331b.jpg)

¿Algo así?

**Comment by jeissonh** [comment]
Sí, pero dándole un giro de 90 grados a los espacios para los tubos, pues los bytes van en secuencia. Creo que ya nos estamos acercando a una excente representación de la memoria :)

**Comment by aph26** [comment]
#15 Con respecto al giro de los tubos, no entiendo si se refiere a cada carril o trabajarlo algo así: 
![boceto_tubos_verticales](https://cloud.githubusercontent.com/assets/9001568/7103638/09a53884-e06e-11e4-8413-215715c13fc5.jpg)

**Comment by jeissonh** [comment]
![stdinout](https://cloud.githubusercontent.com/assets/5830477/7103767/af0fae1e-e085-11e4-8cd8-a14678c1c156.jpg)

La idea de que los tubos bajen está bien (en círculo verde). La idea de que los tubos giren en las salidas/entradas (en círculo rojo) no es conveniente. Esta parte es mejor como estaba originalmente. Pura vida!

**Comment by aph26** [comment]
Ya modifiqué los tube_in y el tube_out, algo así se verían en la pantalla...
![vista previa_tubos](https://cloud.githubusercontent.com/assets/9001568/7103996/a12a1952-e07f-11e4-91cd-44a33dd85cd5.jpg)

**Comment by jeissonh** [comment]
Mucho mejor!

Se me ocurre que para hacerlo más realista, se puede hacer que los tubos se incrusten en la mesa. Si es necesario podemos partir la mesa en dos. Una parte superior donde iría la memoria (más estantes) y la parte inferior con las patas y los tubos.

**Comment by aph26** [comment]
![incrustados](https://cloud.githubusercontent.com/assets/9001568/7205347/eaaa7260-e4e5-11e4-9aff-2ee01e1cc62f.jpg)

**Comment by jeissonh** [comment]
Bien. Se ve un poco más real, pues los tubos están sobre la mesa y en la imagen anterior, se doblan y pasan frente a ella, un efecto "Escher". Ahora que se incrustan se ven un poco más real. Se me ocurren dos mejoras:

1. Los tubos abajo tienen dos rectángulos grises cada uno. Reemplazar el superior por una "pega" naranja, de tal forma que el codo quede simétrico (ver rectángulo y flecha roja abajo)
2. Que en la parte donde se incrustan los codos no sea una línea recta, sino curva, para dar la sensación de redondo (ver las zonas amarillas en la imagen de abajo).

![tubes-into-table](https://cloud.githubusercontent.com/assets/5830477/7205718/3b291864-e4f9-11e4-8818-2f594b8fdb59.png)

**Comment by aph26** [comment]
![previa_share_table_tubes](https://cloud.githubusercontent.com/assets/9001568/7304098/36fd5ba2-e9b2-11e4-9dfb-841862449abb.jpg)

**Comment by jeissonh** [comment]
Genial. Hay que eliminar los estantes verticales de la mesa. Este espacio yo lo relleno con shelf_middle.svg. Es decir, el área sobre los tubos podría eliminarse por completo. La imagen de la tabla reduciría su altura a sólo de la altura que va de los tubos hasta las patas de la mesa.

Otra mejora que se puede agregar es redondear los tubos al final (extremo izquierdo del tube_in y extremo derecho del tube_out). También hay como un pico punteado hacia adentro. Este podría unirse con el fondo con el fin de hacerlo más realista.

Muchísimas gracias, Arturo!

**Comment by aph26** [comment]
![27-apr-15 7-01-51 am](https://cloud.githubusercontent.com/assets/9001568/7348052/6300d6c4-ecab-11e4-80a5-544308af3d85.jpg)

Algo así?

**Comment by jeissonh** [comment]
Sí, pero hay que dar la sensación de continuidad de la mesa. Es decir, no se debe ver el piso a través o en medio de los tubos in/out. La idea es que el estante (shelf_middle.svg) esté sobre la mesa y no que la mesa se acabe antes, pues parece que el estante queda en el aire.

Con todo, no se necesita alargar la mesa hasta las estaciones de trabajo, sino hasta el punto donde inicia el estante.

Algo que estoy pensando es que los estantes se ven muy oscuros y hace que el juego se vea "muy nocturno". Creo que es mejor aclararlos, o hacer los estantes de gris claro a gris oscuro, en lugar de gris oscuro a negro. Voy a abrir otro issue para esto último.

**Comment by aph26** [comment]
![vista previa share table](https://cloud.githubusercontent.com/assets/9001568/7404322/37ee11e6-ee9e-11e4-8872-1c9459dabf2d.jpg)

**Comment by jeissonh** [comment]
Está mejor, gracias.

Aún tenemos un problema de perspectiva y es que la mesa parece vista desde una cámara inclinada, mientras que el estante de una cámara perpendicular. Yo creo que esto es mejor dejarlo así, pues para el prototipo no es tan relevante. Quizá algo sencillo que puede ayudar es extender el borde del shelf_left y shelf_right en la mesa (marcado con la flecha roja). Los tubos in/out se pueden hacer ligeramente más cortos y redondos en los extremos. Agregué una zona amarilla para dar más sensación de que ahí termina el tubo en el fondo:

![tubes-inout-round](https://cloud.githubusercontent.com/assets/5830477/7404504/d063ca34-eeb1-11e4-84d2-0818de5f0a07.png)

**Comment by aph26** [comment]
sí ese problema de perspectiva no solo afecta la relación espacial entre estante y mesa, sino que en un sentido lógico el respaldar de los estantes quedaría hacia los robots, y esto  les imposibilitaría el acceso... 

Con respecto a los shelf_right y el left, hago una versión nueva más corta para el estante de abajo en la mesa? Pregunto porque pienso que la proporción que tienen los de arriba es bastante agradable visualmente:

![shelf_sides_actual_size](https://cloud.githubusercontent.com/assets/9001568/7404723/a818981e-eea4-11e4-8a5e-52ab242f8cd1.jpg)

**Comment by jeissonh** [comment]
Sí, lo ideal es que el estante también esté desde una perspectiva inclinada, es decir, como si una cámara inclinada le hubiera tomado una foto. Pero por ahora, dejémoslo así...

Yo dejaría los anchos del shelf_left y shelf_right intactos. Quien reduce su ancho son los tubos. No sé cómo se vera, ni si tiene sentido. Es sólo una idea que se me ocurrió...

**Comment by aph26** [comment]
el efecto de perspectiva inclinada se logra si le añadimos techo a los estantes, pero durante el proceso se eliminó para ganar espacio. Lo reintegramos también o los dejamos así? 

Eje:
![techo_estante](https://cloud.githubusercontent.com/assets/9001568/7405469/204161c6-eeb0-11e4-89a5-c6c9e7e0f855.jpg)

**Comment by jeissonh** [comment]
Ahhh! eso era un techo....

Creo que los nuevos estantes no ocupan techo, sino dar la sensación de ser abiertos. No agreguemos techo por el momento...
