### ISSUE TITLE
Improve design of game icon

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#33]
Arturo, es el tercer icono de la aplicación, el de la esquina inferior izquierda, que me habías mostrado por correo. Aún no está en el repositorio.

**Comment by aph26** [comment]
Bueno parece que sí pude con lo del commit...

**Comment by jeissonh** [comment]
Usted le agregó los inkscape:label y inkscape:groupmode manualmente al archivo icon.svg o lo hizo AI?
