### ISSUE TITLE
Solution data types: array union struct

### ISSUE THREAD

**Issue by aph26** [citic/botNeumann#65]
Aquí se ve la idea anterior para los arrays y la nueva. Y lo que  le había mencionado antes de la consideración del segmento de la unión pensado para que también almacene algún byte, en caso de usar la unidad (x) completa y no a la mitad. ¿Entonces procedo a diseñarlos de esta nueva forma? 

![nueva unio](https://cloud.githubusercontent.com/assets/9001568/7103666/103123a6-e06f-11e4-89c4-ed527640bf67.jpg)

**Comment by jeissonh** [comment]
Sí por favor. Es mejor que la unión sea de `x` y no de `1/2 x`. Gracias.
