### ISSUE TITLE
Cropping instead of clipping shelf_*.svg

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#7]
Las imágenes shelf_left.svg, shelf_middle.svg y shelf_right.svg contienen todo el estante, pero clipped a un rectángulo visible. Para el software, escalar imágenes clipped requiere mucha memoria. Lo ideal es no hacer clipping, sino cropping. Cropping significa eliminar lo que está en la zona no visible.
Aunque haya pérdida de datos, es mejor para optimizar el manejo del gráfico cuando el juego corre. La imagen original, con el estante completo, continúa en el archivo .ai, la cual podríamos compartir por Dropbox o Google Drive.

Yo reconstruí un shelf_middle.svg utilizando rectángulos y líneas. No coincide con shelf_left.svg y shelf_right.svg, por lo que se ve una diferencia (en las capturas de pantalla o al correr el programa). El nuevo shelf_middle.svg que hagas, si quieres, puede ser más ancho que shelf_left.svg y shelf_right.svg. En teoría, no debe haber ahorro de memoria en proporción a su ancho. Si la quieres hacer más ancha, que no sea más de 1/4 del ancho global (1024). Yo sugiero dejarla del mismo ancho (el correspondiente a un dato de 1 byte).

Las imágenes de las esquinas del estante (shelf_bottom_left, ...), no están siendo usadas por el juego. Pueda que sea mejor optimizar estas tres (shelf_left.svg, shelf_middle.svg y shelf_right.svg) para que generen un mosaico perfecto. Si se requiere un borde, yo lo puedo dibujar mediante software, o bien, tener un .svg con un único rectángulo que sólo sea el borde.

Arturo, indícamente si, además de las imágenes de los estantes, hay otras imágenes con clipping en el repositorio.

**Comment by aph26** [comment]
Probemos con esos nuevos ajustes. Ya no son clippings. Y creé un segmento adicional de dos middles (shelf_middle_x2.svg) para que experimentemos si funciona mejor. En teoría deben calzar como en la imagen ▼
![previa_shelf](https://cloud.githubusercontent.com/assets/9001568/6828029/0d6d7bfc-d2d1-11e4-9706-20414ec21830.jpg)
.

**Comment by jeissonh** [comment]
No veo el commit con las nuevas imágenes...
