### ISSUE TITLE
Extract shelf_separation.svg from shelf_middle.svg

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#81]
From comment in issue #17: Tenemos un problema con la separación entre estantes. No puede haber una separación entre el byte 0 y el byte 1. Se me ocurre que la separación, debe estar independiente, en su propia imagen, cuyo ancho es el de 1 byte. El shelf_middle ocuparía 7 un ancho de bytes. De esta forma, yo asigno las separaciones mediante software.

**Comment by aph26** [comment]
Listo...
