### ISSUE TITLE
Update design according to the new shelves

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#82]
![botneumann-0419](https://cloud.githubusercontent.com/assets/5830477/7222992/c0c94436-e6e7-11e4-815b-5ac37a823ba8.png)

The rest of elements, mainly the work stations, should be have an according style to the new shelves.

**Comment by aph26** [comment]
¿Solo son 2 mesas?

**Comment by aph26** [comment]
Hasta el momento, esta seria una vista previa de lo que llevamos... Con las nuevas especificaciones de los estantes se ganó espacio... Entonces no sé si quiere mesas de trabajo más grandes o intentamos que en la mesa compartida entren datos de 8 bytes?

![pantalla](https://cloud.githubusercontent.com/assets/9001568/7304921/84656862-e9b7-11e4-9016-f20b59f0f253.jpg)

**Comment by jeissonh** [comment]
La cantidad de mesas se ajusta dinámicamente desde el software. Normalmente será un número entre 1 y 4. Para el diseño gráfico asumamos que son 4, como hiciste en esa última imagen.

La altura de cada sección del escenario (memoria dinámica, estaciones de trabajo, y tabla compartida) se ajustan dinámicamente. Igual la cantidad de estantes que tienen cada una de ellas. Estos números se calculan dinámicamente, cuando el software está corriendo, y depende de la cantidad de memoria que la unidad requiere para que el problema se solucione. El software no lo sabe de antemano, sino cuando carga la unidad. Lo grandioso del SVG es que podemos estirarlo y ajustarlo a estas necesidades sin pérdida de calidad.
