### ISSUE TITLE
Memory interface must be attached to dynamic memory area

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#83]
La interfaz que usan los robots para poner datos en la memoria dinámica, es parte de la memoria dinámica, no de las estaciones de trabajo. El diseño gráfico debería dar la impresión de que es parte de la parte superior. En la imagen de abajo la zona que está debajo de la flecha no debería ser vacía :)

![dyn-mem-interface](https://cloud.githubusercontent.com/assets/5830477/7320449/9877b2b6-ea6a-11e4-9363-2c353feff4ee.png)

**Comment by aph26** [comment]
Esto me pregunto si se resuleve mediante la sobreposición de planos con programación o tengo que diseñar un shelf_bottom que ahora incluya esta sección de la división?

![previa](https://cloud.githubusercontent.com/assets/9001568/7404591/68c2696c-eea2-11e4-8179-014f57922624.jpg)

**Comment by jeissonh** [comment]
Yo puedo superponer planos, no es necesario dibujar un shelf_bottom :)

Me parece muy bien que ya esté pegado a la memoria dinámica, pero no podemos tapar el centro del último shelf. Estaba pensando y se me ocurrió una idea que incluso hace la programación más fácil.

Si dejamos esa interfaz como está, los datos que vienen de o van a la memoria dinámica, hay que rotarlos 90 grados y hacerlos pasar por el orificio, luego rotarlos de nuevo (eso podría requerir más imágenes). Es más fácil si en lugar del orificio dejamos un boquete del ancho de 8 bytes y el boquete tiene la misma forma que el boquete de uno de los tubos in/out. Podríamos pensar que es el boquete de una ventanilla de banco, que tiene como una "cesta" para poner las monedas/billetes, etc. Esa cesta sería el tubo cortado a la mitad. Así yo tomo los datos y los ubico en sus estantes sin tener que rotarlos.

![dynamic-memory-interface](https://cloud.githubusercontent.com/assets/5830477/7404856/aee29bd2-eeb7-11e4-8c86-8ee8727e201d.jpg)

La interfaz entonces puede ser una franja horizontal (un rectángulo), con la abertura en algún lugar. No tiene que ser necesariamente en el centro. La interfaz funciona de la siguiente manera.

* Para leer un dato de la memoria dinámica, un robot pone un número en la dirección y presiona el botón de leer (flecha hacia abajo). La animación consigue el valor, trae una copia y la deja caer en el tubo data. El robot toma el dato leído y lo coloca en su mesa.

* Para escribir un dato en la memoria dinámica, un robot pone un número en la dirección, un dato en el tubo "data" y presiona el botón write (la flecha hacia arriba). La memoria toma el dato y lo pone en la dirección dada, sobrescribiendo lo que había antes ahí.

Los robots hacen esas interacciones telepáticamente.

**Comment by aph26** [comment]
Anteriormente habían unas pantallas, debo considerarlas también o ya no?

**Comment by jeissonh** [comment]
Estoy perdido... ¿cuáles pantallas?

Otras sugerencias de última hora.

* La altura de la interfaz no tiene que ser muy grande. Se puede reducir de la actual para ganar espacio.
* Los botones con flechas (write, read) creo que es mejor intercambiarlos: (read, write).
* La dirección es algo que ocupa la memoria dinámica para saber dónde leer o escribir. No es un dato que debe animarse una vez que atraviesa la interfaz. Por esto no requiere una abertura. Bien podría dársele un efecto de que entra a la interfaz, digamos, como una zona hundida indicando que entra en la interfaz y se queda ahí. Yo la hago desaparecer incrementándole su transparencia gradualmente.
* Así como la dirección, hay otro valor que estoy dilucidando si es necesario: el tamaño de los datos (size). Yo creo que es mejor tenerlo. Iría entre address y data. Tendría el mismo diseño que el address.

Muchas gracias Arturo.

**Comment by aph26** [comment]
Esas pantallitas 
![previa](https://cloud.githubusercontent.com/assets/9001568/7405327/711ccb96-eeae-11e4-9bcd-4cf6a63cf1f9.jpg)

**Comment by aph26** [comment]
Ignore la pantalla si no es necesaria, pero tal vez a modo de idea, animar la salida de los datos sea interesante... 
![escotilla](https://cloud.githubusercontent.com/assets/9001568/7405336/7a87549e-eeae-11e4-8de8-8495ebf6bdbc.gif)

**Comment by jeissonh** [comment]
Esas pantallitas no son necesarias. De hecho, pensaba que eran adornos...

Me encanta ese estante del gif animado. Parece que fue tomado por una cámara inclinada. Si cambiáramos los estantes que tenemos a ese diseño, habría que apilarlos unos encima de otros. Lo que en inglés llaman un "rack". Se podrían usar dos varillas de aluminio delgadas verticales para sostener el rack a cada extremo. En la parte superior sí se podría poner un techo, ahí sí tendría sentido...

El efecto de animar la salida o entrada de los datos en la interfaz de esa forma me gusta. Parece que hay una pequeña puerta semi-giratoria, de esas que tienen resortes (invisibles) y se abren cuando se empujan con poca fuerza, como las de algunas unidades de CD-ROM.

Con todo la pantalla podría ser útil para indicar al usuario la dirección donde se está leyendo o escribiendo. La pantalla sería para la dirección (address) y otra para el tamaño (size). Se me ocurre que la compuerta para ambas podría ser la pantalla misma. La compuerta para el dato (data) sería opaca, no una pantalla...

Pura vida!

**Comment by aph26** [comment]
A ver qué tal así lo de los "racks"? 

![rack_preview](https://cloud.githubusercontent.com/assets/9001568/7445697/faacb94c-f17a-11e4-9918-8153d2086e58.jpg)
![rack_preview2](https://cloud.githubusercontent.com/assets/9001568/7445699/00387842-f17b-11e4-85ad-a02fc685a5e9.jpg)

**Comment by jeissonh** [comment]
Esos de abajo se ven maravillosos. Pero quedémonos con los de arriba. Para que los de abajo se vean bien, hay que tener muchas imágenes para poder manejar bien el eje z (profundidad). Para el prototipo los estantes de arriba funcionan bien y son mucho más fáciles de programar.

Al techo hay que aplicarle la perspectiva. En lugar de ser un rectángulo, hay que convertirlo en un trapecio.

En la parte frontal de los estantes yo debo escribir números (direcciones de memoria) y creo que sí caben. Creo que también podemos reducir la altura entre estantes y ahorrar un poquito de espacio vertical.

Estos nuevos estantes funcionan mejor para el segmento de datos (la mesa compartida). Ahora los tubos de entrada y salida quedarían debajo de los estantes y los robots pueden tomar los datos por cualquier lado, no sólo el frente.

Lo que cambia bastante ahora son las estaciones de trabajo. Cada robot estaría trabajando con un pequeño rack de estos en frente. Los estantes antes se apilaban unos sobre otros verticalmente (eje y), pero ahora hay que apilarlos en el eje z, es decir, el robot sólo trabaja con un rack, y los demás quedan detrás de ese. Creo que ese efecto es fácil de lograr con los techos de los rack, pues los techos son los que se verían apilados y de frente sólo el rack que está en la parte superior. Nota: a un robot sólo se le permite acceder a un rack a la vez: el que está frente a él.

Excelente trabajo Arturo, muchas gracias!

**Comment by aph26** [comment]
ok a ver si entendí bien lo de este nuevo replanteamiento... Al final la pantalla se debería ver como algo asÍ?

![boceto](https://cloud.githubusercontent.com/assets/9001568/7574291/7229a54c-f7e9-11e4-80d4-1e05b8a0442c.jpg)

**Comment by jeissonh** [comment]
Exacto, retrataste genial la idea!

Estoy pensando cómo le hace un robot cuando necesita un nuevo "rack", es decir, ¿de dónde lo saca? Se me ocurre que lo saque del piso. Así como hay una compuerta (tipo CD-ROM) que se abre cuando vienen datos de los estantes del fondo, podría haber una compuerta en el piso del robot con dos botones de flecha. El robot empuja los racks hacia el fondo y activa la puerta presionando el botón con flecha hacia arriba (con animaciones, le manda un rayo al botón) y de ella sale y sube un rack.

Parecería natural que los racks tengan ruedas (pero dejémoslos sin ellas para el protitipo) y en el suelo hay rieles que permiten a los racks desplazarse en el eje z (esos serían los nuevos "workstations"). El número de racks que caben en los rieles es limitado y yo lo controlo por software, normalmente serán entre 4 y 8.

Para deshacerse de un rack, el robot enviaría su rayo hacia el botón de flecha abajo, la compuerta en el piso se abre y el rack frontal cae... La compuerta se cierra y los racks activos se corren hacia adelante.

¿Qué te parece?

**Comment by jeissonh** [comment]
Por cierto, en medio de los robots deben haber tabiques. Es decir, las estaciones de trabajo deben estar separadas como estaban antes. La idea es que los robots no puedan ver el trabajo de otros. Los robots no se hablen entre ellos directamente.

Muchas gracias!

**Comment by aph26** [comment]
Así se va viendo lo discutido... Añadí lo de las puertas que que me había mencionado hace un tiempo atrás, y a estas les hice ventanales para darles más atractivo visual.  ¿Qué opina? 

![pantalla_1](https://cloud.githubusercontent.com/assets/9001568/7773589/c35af99e-0062-11e5-87e6-d9c2b52050c2.jpg)
![pantalla_2](https://cloud.githubusercontent.com/assets/9001568/7773590/c365b514-0062-11e5-9f14-a634de3ef35a.jpg)

**Comment by jeissonh** [comment]
Muy bien! Ya casi estamos listos :)

Sugerencias.

1. Los rieles pueden ser menos largos. Deberían tener el largo de 8 techos apilados, como se ve para el primer robot, es cerca de 1/3 del largo actual de los rieles.

2. La interfaz para la memoria dinámica no debe ser parte de los tabiques, debe estar arriba de ellos. Si el número de techos para los robots del centro crece, taparán a los botones. Estos botones siempre deben estar disponibles.

3. La interfaz debe constar de 3 compuertas (address, size, data) y dos botones flecha: read (v) y write (^).

Muchísimas gracias, Arturo!

**Comment by jeissonh** [comment]
Arturo.
Cuándo va a estar disponible este diseño en el repositorio?
Gracias!

**Comment by aph26** [comment]
Saludos Jeisson,

Es muy probable que para esta semana ya esté subiendo todos los assets del unit_playing. 
En el caso de los nombres asignados a cada elemento del unit_playing, es solo de sobre escribir el archivo viejo por el nuevo cierto, o debo añadir nuevas denominaciones como por el ejemplo en el caso del "rack"?

**Comment by jeissonh** [comment]
Ciertamente el término "rack" es ahora más preciso que "shelf". Creo aún que es mejor utilizar los nombres que los conceptos que representan dentro de la computadora. Aunque cambiemos la metáfora, siempre los conceptos de programación serán constantes. Es decir, propongo estos cambios:

	robotN_* -> threadN_*
	shared_table -> data_segment
	shelf_interface -> heap_segment_interface
	shelf_separation -> [DELETE]
	shelf_* -> memory_row_*
	shelves_closed -> heap_segment_disabled
	tube_in -> standard_input_[left|middle|right]
	tube_out -> stardard_output_[left|middle|right]
	workstation -> [DELETE]
	workstation_frame -> stack_segment
	workstation_table -> [DELETE]

En la imagen de abajo señalé qué comprende cada imagen. Aún falta incorporar algunos cambios que te había solicitado tres entradas arriba.

![racks](https://cloud.githubusercontent.com/assets/5830477/8285925/c8c91004-18c3-11e5-8fbd-c0c39c073a72.png)

Muchas gracias, Arturo!

**Comment by jeissonh** [comment]
Muchísimas gracias Arturo. Estoy ajustando el código fuente a los cambios en la metáfora. Estos son cambios que hice en los nombres de archivos de imagen:

	shelves_closed.svg -> heap_segment_disabled.svg
	shared_table.svg -> [DELETED]
	stack_segment_rack.svg -> [DELETED]
	robotN_*.svg -> threads/threadN_*.svg
	wave.svg -> threads/wave.svg	
	
Nota que los robots los envié a una subcarpeta `threads/`. Así la carpeta `unit_playing` queda con menos archivos y por tanto, más orden.

**Comment by aph26** [comment]
De momento algo así es como se va viendo la pantalla.Ya con un nuevo diseño de suelo, más simple y espero que ligero... 
![preview_screen](https://cloud.githubusercontent.com/assets/9001568/8809944/c3af3cf0-2fa8-11e5-98cd-8fc7675ee7b3.jpg)

**Comment by jeissonh** [comment]
Me gusta el diseño del piso.

Recuerda uniformar el tamaño de la barra de título en `unit_selection/background.svg` y `unit_playing/background.svg`.

Muchas gracias

**Comment by aph26** [comment]
Listo, uniformados...
