### ISSUE TITLE
Reduce darkness on shelves

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#84]
Los estantes se ven muy oscuros y hace que el juego se vea "muy nocturno". Creo que aclararlos incrementa la legibilidad. Es decir, hacer los gradientes de los estantes de gris claro a gris oscuro, en lugar de gris oscuro a negro.

**Comment by aph26** [comment]
◄ Antes   ► Ahora
![29-apr-15 6-39-32 pm](https://cloud.githubusercontent.com/assets/9001568/7404393/2330d95e-ee9f-11e4-8a32-15e35203ffd4.jpg)

**Comment by jeissonh** [comment]
Los gradientes del "antes" parecen tener 2 "stops": de gris a negro. Me parece que los gradientes del "ahora" tienen 4 "stops": gris claro, gris oscuro, gris medio-oscuro, gris oscuro. Necesitamos que los gradientes se parezcan a los gradientes del "antes" con "2 stops", pero incluso hasta pueden ser grises más claros.

Si es muy complicado, podemos seguir con los negros y yo cambio el color de la fuente a colores "fosforescentes" o blanco.

Pura vida, Arturo!
