### ISSUE TITLE
Callout to have robot speaking

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#87]
Arturo. Para poder comunicar el relato (trama) del juego al jugador, pienso que podemos hacer hablar el robot que aparece en la escena `game_menu`. Para ello necesitamos un globo como los que se utilizan en caricatura:

![robot-callout](https://cloud.githubusercontent.com/assets/5830477/8602241/7ea0cca6-262e-11e5-9520-7a1cef1ea193.png)

El nombre del archivo podría ser `callout.svg` y ya que se utiliza en muchas escenas, coloquémoslo en la carpeta `assets` directamente.

Muchas gracias

**Comment by jeissonh** [comment]
En cuanto a aspectos de diseño, creo que necesitamos dos: `callout_left` (como el de arriba) y `callout_right`, que varían simplemente en la dirección de la flecha. Puedes darle el estilo futurista que consideres adecuado.

**Comment by jeissonh** [comment]
Las dimensiones por defecto del callout pueden ser:
* width: la mitad del alto de la pantalla: 720/2 = 360px.
* height: un sexto del alto de la pantalla: 720/6 = 120px

**Comment by aph26** [comment]
![17-jul-15 8-51-08 am](https://cloud.githubusercontent.com/assets/9001568/8749778/fe5f635c-2c60-11e5-8ee0-8d17278a9824.jpg)

**Comment by jeissonh** [comment]
Me gusta el diseño futurista. Necesitamos hacerle el borde mucho menos grueso. La altura del globo debe redimensionarse de acuerdo a la longitud del texto. A veces los textos son un poco largos. Este es el más largo hasta el momento y te puede servir para probar:

> Como ya debe saber por las noticias, un grupo de hackers esperaron estratégicamente esta fecha, el año 3000, para explotar varias vulnerabilidades del InterServ. El InterServ es el nombre del sistema que controla varios servicios públicos internacionales, como transporte y comunicaciones. El InterServ fue construido por el esfuerzo de cientos de programadores en C/C++ durante más de 400 años. Consta de millones de unidades intercomunicadas que realizan tareas sencillas.

Si el globo se hace grande, el borde se hará desproporcionado. Quizá un borde con relieve pero muy angosto haga el trabajo :)

Muchas gracias Arturo

**Comment by aph26** [comment]
Adelgazando la estructura del contorno del globo, me surgió la duda de si el formato que me señaló anteriormente de (360 px x 120 px) incluye la colilla del globo de texto, o esa dimensión se refriere al área para añadir texto? 

El cuadro blanco es el formato. •Izq. Todo dentro de ese formato. •Der. Solo el globo de texto, la colilla queda por fuera. (Dando más espacio de escritura).
![globo_texto](https://cloud.githubusercontent.com/assets/9001568/8810133/2d1cce40-2faa-11e5-80f3-7a8d10879aea.jpg)

**Comment by jeissonh** [comment]
El tamaño era sólo una sugerencia. Dado que inicialmente no pensé que algunos textos iban a ser largos, nos sirve más el diseño de la derecha.

Idealmente el globo constaría de tres partes: top, center y bottom, para hacerlo crecer verticalmente sin perder la perspectiva. Pero por el momento quedémonos con sólo uno para cada dirección de collila (left y right), en lugar de seis.

Muchas gracias

**Comment by aph26** [comment]
Listo, por aquí... 
![callout_parts](https://cloud.githubusercontent.com/assets/9001568/8907139/473d41de-3431-11e5-92c5-d59f4b953171.jpg)
