### ISSUE TITLE
A way to report if output is valid

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#89]
Necesitamos alguna forma de indicarle al usuario si la salida es válida o no. Se me ocurre que el `standard_output` cambie de color: dorado/verde/rojo, donde dorado es que no hay actividad, rojo que se espera salida o la salida es inválida, y verde que la salida es válida.

Otra metáfora es usar un semáforo o algún tipo de control industrial que utilice los colores verde/rojo.

**Comment by aph26** [comment]
![17-jul-15 8-19-36 am](https://cloud.githubusercontent.com/assets/9001568/8749167/027cd036-2c5d-11e5-8592-5f9f185535f7.jpg)

**Comment by aph26** [comment]
Algunas de las posibles soluciones para añadir las luces...

![op_tubos_out](https://cloud.githubusercontent.com/assets/9001568/8754839/8c7610e2-2c83-11e5-9833-85d2e9df3cf2.jpg)

**Comment by jeissonh** [comment]
La primera opción debemos descartarla, porque la cantidad de datos que se visualicen saliendo pueden ser más de 13 o más que el espacio que haya en pantalla. La idea es muy buena y ayuda al estudiante a saber cuál dato falló, pero es difícil programarlo, ya que para la computadora es un torrente de bytes: con sólo uno que esté incorrecto, toda la salida se considera incorrecta.

La segunda opción me gusta porque el bombillo parece estar conectado con algo que viene de afuera. Como si otra oficina se afectara por los datos erróneos que esta oficina le envía por el tubo neumático. Lo que no me gusta es que hay que consumir espacio para dejar claro que el bombillo está relacionado con la salida estándar y no con la entrada.

Me quedo con la tercera opción. Consume muy poco espacio y deja muy claro que la luz está asociada a la salida estándar. Parece un monitor/verificador que trabaja en esta oficina más que en otra, pero creo que el concepto será claro para el estudiante.

Las dos luces en la parte inferior no son necesarias. Quedaríamos con solo una luz. Es como esas lámparas que tienen dos bombillos de colores dentro y por tanto la misma lámpara puede alumbrar de distinto color dependiendo de cual bombillo está encendido. Entonces sólo necesitaríamos tres juegos de luces:

1. `standard_output_test_inactive` en naranja apagado, cuando no hay actividad.
2. `standard_output_test_invalid` en rojo encendido, cuando pasa un resultado incorrecto.
3. `standard_output_test_valid` en verde encendido, cuando pasa el resultado esperado.

Muchas gracias Arturo.

**Comment by aph26** [comment]
Añadí este segmento extra, para poder conseguir el acople visual del área compartida del rack "share table", en la versión "left" y la versión "right" 
![segmento_extra](https://cloud.githubusercontent.com/assets/9001568/8762410/5cbd5038-2d35-11e5-87f0-646b72ab4109.jpg)

**Comment by jeissonh** [comment]
Podemos hacer que `memory_row_right` tenga las patillas arriba, en lugar de abajo. Así nos evitamos tener que introducir nuevas imágenes.

Hay que probar que funcione.

**Comment by aph26** [comment]
![preview](https://cloud.githubusercontent.com/assets/9001568/8809912/9d92b22c-2fa8-11e5-9c70-4d89a7a4e831.jpg)

**Comment by jeissonh** [comment]
Bien! Esto nos ahorra tener que hacer imágenes diferenciadas para el último estante.

Ahora nos queda inventar algo para el estante en el segmento de pila -el estante que está frente al robot-. Ese requiere tener patas. Pero además, necesitamos inventar una puerta en el piso, de tal forma que el robot puede pedir que se agreguen o eliminen estantes con los botones flecha arriba y flecha abajo (los mismos de la interfaz de la memoria dinámica). Esto último puede ser para un nuevo issue.

Muchas gracias!

**Comment by aph26** [comment]
a modo de boceto se me ocurre que podría ser algo así... Cómo lo ve?

![boceto puerta](https://cloud.githubusercontent.com/assets/9001568/8910331/5c22bec8-3443-11e5-8ead-d5dcea2d088d.jpg)

**Comment by aph26** [comment]
También me pregunto si no es más sencillo desde el asunto de la programación y demás, trabajar estos racks como un solo objeto en ves de estar compuesto por secciones... Así no habría que incluir el "memory_row_bottom.svg" (las patas en un segmento a parte). 

![rack_compuesto](https://cloud.githubusercontent.com/assets/9001568/8910462/1ce5e5fe-3444-11e5-9d84-a7ab62ed11a2.jpg)

**Comment by jeissonh** [comment]
El número de estantes en un 'rack' se calcula dinámicamente, de acuerdo a la cantidad de memoria que tenga la unidad configurada. De antemano no sabemos cuántos estantes tendrá cada rack, por eso yo los construyo desde el software. Me parece que el piso de los rack en el segmento de pila está sobrecargado. Se me ocurre esta propuesta:

1. Quitar las dos decoraciones de franjas amarillas/negras.
2. Dejar la línea zig-zag que da impresión de que hay una puerta.
3. Dar la sensación de las dimensiones de la puerta con un rectángulo en el piso (por la perspectiva, un trapecio)

![stack_frame_door](https://cloud.githubusercontent.com/assets/5830477/8912730/f30fed52-3451-11e5-994d-3784b5ba6bb2.png)

Para poder animar la compuerta cuando se cierra o abre, necesitaríamos unas cuatro imágenes: cerrada, 33% abierta, 66% abierta y 100% abierta. La abertura en lugar de ser un agujero negro, podría dar sensación de un sótano. Es decir, que al abrir la puerta, podemos ver un pedazo de una pared del mismo color del piso.

**Comment by aph26** [comment]
![gates](https://cloud.githubusercontent.com/assets/9001568/9065875/902d3c4e-3a91-11e5-852b-f0f2f76b5045.jpg)

**Comment by jeissonh** [comment]
Bien! Ahora debemos darles nombres:

* stack_segment_allocator_closed
* stack_segment_allocator_open33
* stack_segment_allocator_open66
* stack_segment_allocator_open_upper
* stack_segment_allocator_open_lower

![stack-segment-allocator](https://cloud.githubusercontent.com/assets/5830477/9067931/9081a3c2-3a9d-11e5-8597-8577a74ae7aa.png)

La imagen de la puerta abierta necesitamos dividirla en dos. Es para que los racks entren o salgan por ella y -jugando con la profundidad (eje z)- provocar la sensación de que se insertan en la puerta. No sé si habrá un modo más fácil de lograr el mismo efecto.
