### ISSUE TITLE
Rearrange doors and buttons in dynamic memory interface

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#91]
En la interfaz de la memoria dinámica, las puertas y los botones read/write deberían quedar en este orden:

	   [     ] [     ]  [v] [     ]  [^] 
	   Address   Size  Read  Data   Write 

Es para facilitar la animación del robot, pues acciona esos componentes en ese orden.

Muchas gracias!

**Comment by aph26** [comment]
Ok, reorganizado el espacio (señalando una prevista de dónde deben ir los botones). Según lo discutido los botones se iban a trabajar de manera aislada, para poder alternarlos cuando estos estuvieran activos o no. Los nombré de la siguiente forma: 
"button_read_on.svg"
"button_read_off.svg"
"button_write_on.svg"
"button_write_off.svg"

![heap_segment_buttons](https://cloud.githubusercontent.com/assets/9001568/8907180/8549694e-3431-11e5-8206-40d24c156892.jpg)
