### ISSUE TITLE
Sticker for variable names

### ISSUE THREAD

**Issue by jeissonh** [citic/botNeumann#92]
Necesitamos una forma de indicar el nombre de las variables. Se me ocurren dos opciones. Una es utilizar los estantes, lo cual lo controlo yo desde software. La segunda es utilizar "pegatinas" sobre los datos. Es algo así como pegar una cinta adhesiva semitransparente sobre el dato y escribirle el nombre de variable con un "pilot". Por ejemplo, las variables `a` y `b` siguientes (con diferentes valores):

![variable_name](https://cloud.githubusercontent.com/assets/5830477/8812734/2bf59432-2fbb-11e5-8ae3-9e0c3db59c43.png)

La idea es provocar apariencia de una adhesiva. La podemos almacenar en  `unit_playing/data_types/variable_name.svg`. Idealmente requeriría estar dividida en 3 partes: left, middle y right, porque debería crecer horizontalmente de acuerdo a la cantidad de caracteres del nombres. Los nombres yo los escribo mediante software.

Muchas gracias!

**Comment by aph26** [comment]
Algo así, es lo que le entendí... Siento que al presentarlo al tamaño del 100%  hay problemas para comprender la idea del sticker o cinta adhesiva. Existirá alguna opción de aumentar (zoom) esa parte de la pantalla para el usuario? 

![stickers_view](https://cloud.githubusercontent.com/assets/9001568/8910161/6cc16b86-3442-11e5-8c6c-5f646ffedb2c.jpg)

**Comment by jeissonh** [comment]
Me gusta el diseño de las adhesivas. El zoom se ajusta automáticamente de acuerdo al tamaño de la pantalla o de la ventana del usuario. Eso es una ventaja de trabajar con imágenes vectoriales. Con todo, creo que se puede hacer la adhesiva 1px más alto. Necesitamos ajustar el ancho de cada segmento de la adhesiva:

![variable_name_slice](https://cloud.githubusercontent.com/assets/5830477/8912004/fc0f7d1e-344c-11e5-953f-72d0f633ad87.png)

El extremo del centro es el que yo estiro o encojo de acuerdo al ancho del nombre de la variable. Por eso el left y el right deben ser muy angostos. Yo no hago un mosaico con el middle, sino que lo estiro.
